sonar.projectKey=caly-control
sonar.projectName=Caly Vision Ótica
sonar.projectVersion=1.0.0
sonar.host.url=http://localhost:9000

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=17
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/OticaApplication.java,\
  **/config/DataInitializer.java,\
  **/shared/audit/AuditableEntity.java,\
  **/*Repository.java,\
  **/*Form.java,\
  **/domain/**/*Controller.java,\
  **/config/*Controller.java

sonar.test.inclusions=**/*Test.java,**/*Tests.java
