spring.application.name=otica

# Perfil ativo (sobrescrito por variável de ambiente em produção)
spring.profiles.active=dev

# Configurações de sessão
server.servlet.session.timeout=30m

# Thymeleaf
spring.thymeleaf.cache=false
